import assert from 'node:assert/strict';
import fs from 'node:fs';

const html = fs.readFileSync(new URL('../src/core/sidepanel.html', import.meta.url), 'utf8');
const script = fs.readFileSync(new URL('../src/core/sidepanel.js', import.meta.url), 'utf8');

assert.doesNotMatch(html, /id="panel-title"|AI Chat Exporter/);
assert.doesNotMatch(html, /id="site-info"|id="site-info-text"/);
assert.doesNotMatch(html, /id="panel-tools"|id="export-status"/);
assert.match(html, /id="top-info"[\s\S]*id="welcome-tip"[\s\S]*id="pro-action-row"[\s\S]*id="export-format-row"[\s\S]*id="runtime-status"[\s\S]*<div id="outline">/);
assert.match(html, /id="export-format-row"[\s\S]*id="runtime-status" aria-live="polite"[\s\S]*id="rescan-button"[\s\S]*id="retry-locate-button"[\s\S]*id="runtime-status-details-button"/);
assert.match(html, /id="rescan-button"[\s\S]*<svg[\s\S]*id="retry-locate-button"[\s\S]*<svg/);
assert.match(html, /id="bottom-export-btn"[\s\S]*id="help-button"/);
assert.match(html, /id="runtime-status-popover" hidden[\s\S]*id="copy-diagnostics-button"/);
assert.doesNotMatch(html, /id="runtime-status-popover"[\s\S]*id="rescan-button"|id="runtime-status-popover"[\s\S]*id="retry-locate-button"/);
assert.match(html, /data-i18n="outlineHelpTitle"[\s\S]*data-i18n="outlineHelpOpen"[\s\S]*data-i18n="outlineHelpJump"/);
assert.match(html, /data-i18n="statusHelp"/);
assert.doesNotMatch(html, /id="cancel-repair-button"|id="repair-locate-button"/);
assert.doesNotMatch(html, /pro-mode-label|export-format-hint|更多格式为 Pro 功能|只导出重要问答/);
assert.match(html, /#pro-action-row\s*\{[\s\S]*grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\)/);
assert.match(html, /#top-info\s*\{[\s\S]*flex:\s*0 0 auto/);
assert.match(html, /#outline\s*\{[\s\S]*overflow-y:\s*auto/);
assert.match(html, /#export-format-row label\s*\{[\s\S]*white-space:\s*nowrap/);
assert.match(html, /#export-format\s*\{[\s\S]*flex:\s*1 1 auto/);
assert.match(html, /font-family:\s*-apple-system, BlinkMacSystemFont, "PingFang SC", "Microsoft YaHei", "Noto Sans CJK SC", "Segoe UI", Arial, sans-serif/);
assert.match(script, /const UI_LANGUAGE = browserLanguage\.toLowerCase\(\)\.startsWith\('zh'\) \? 'zh' : 'en'/);
assert.match(script, /zh:\s*\{[\s\S]*en:\s*\{/);
assert.match(script, /function applyStaticTranslations\(\)/);
assert.match(script, /\[data-i18n-title\]/);
assert.match(script, /errorTitle.*supportedSites.*visitSites/s);
assert.match(script, /outlineHelpTitle.*outlineHelpOpen.*outlineHelpJump/s);
assert.match(script, /statusHelp/);
assert.match(script, /function makeRuntimeStatus\(/);
assert.match(script, /function diagnosticText\(/);
assert.match(script, /function statusNeedsAttention\(status\)/);
assert.match(script, /function renderStatusLine\(/);
assert.match(script, /function renderRuntimeStatusPopover\(/);
assert.match(script, /function setRuntimeRecoveryActions\(/);
assert.match(script, /rescanButton\.setAttribute\('aria-label', t\('rescan'\)\)/);
assert.match(script, /retryButton\.setAttribute\('aria-label', t\('retryLocate'\)\)/);
assert.match(script, /function retryLocateTarget\(\)[\s\S]*scrollToOutlineItem\(item\)/);
assert.match(script, /function setLocateRetryAction\(/);
assert.doesNotMatch(script, /repairAndLocate|cancelRepair|repairProgress/);
assert.match(script, /statusNeedsAttention\(nextStatus\) && nextStatus\.status !== 'unsupported'/);
assert.match(script, /if \(status\?\.status === 'ready'\) return status\.summary \|\| ''/);
assert.doesNotMatch(script, /setOutlineReadyStatus|readyChatgpt|readyDoubao|readyOutline/);
assert.match(script, /exportFullCount: '导出完整对话（\{count\} 组）'/);
assert.match(script, /currentOutlineData\.filter\(item => item\?\.type === 'question'\)\.length/);
assert.match(script, /runtime-status-details-button/);
assert.match(script, /function getBoundPanelTab\(\)/);
assert.match(script, /chrome\.tabs\.get\(currentTabId\)/);
assert.doesNotMatch(script, /chrome\.tabs\.onActivated/);
assert.match(script, /if \(tabId !== currentTabId\) return/);
assert.match(script, /Questions indexed:/);
assert.doesNotMatch(script, /URL: \$\{diagnostics\.url\}/);
assert.match(script, /const jumpSerial = \+\+jumpRequestSerial/);
assert.match(script, /url: jumpUrl,[\s\S]*requestToken: jumpRequestToken/);
assert.match(script, /!chrome\.runtime\.lastError && isChatGpt && response\?\.reason === 'target-not-mounted'/);
assert.match(script, /!response\?\.success[\s\S]*locateFailed/);
assert.match(script, /setExportStatus\(t\('located'/);

console.log('sidepanel ui contract ok');
