import assert from 'node:assert/strict';
import fs from 'node:fs';

const html = fs.readFileSync(new URL('../src/core/sidepanel.html', import.meta.url), 'utf8');
const script = fs.readFileSync(new URL('../src/core/sidepanel.js', import.meta.url), 'utf8');

assert.doesNotMatch(html, /id="panel-title"|AI Chat Exporter/);
assert.doesNotMatch(html, /id="site-info"|id="site-info-text"/);
assert.match(html, /id="panel-tools"[\s\S]*id="rescan-button"[\s\S]*id="copy-diagnostics-button"[\s\S]*id="help-button"/);
assert.match(html, /id="runtime-status" hidden aria-live="polite"/);
assert.match(html, /id="runtime-status-actions" hidden[\s\S]*id="repair-locate-button"[\s\S]*id="cancel-repair-button"/);
assert.doesNotMatch(html, /pro-mode-label|export-format-hint|更多格式为 Pro 功能|只导出重要问答/);
assert.match(html, /#pro-action-row\s*\{[\s\S]*grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\)/);
assert.match(html, /#export-format-row label\s*\{[\s\S]*white-space:\s*nowrap/);
assert.match(html, /#export-format\s*\{[\s\S]*flex:\s*1 1 auto/);
assert.match(html, /font-family:\s*-apple-system, BlinkMacSystemFont, "PingFang SC", "Microsoft YaHei", "Noto Sans CJK SC", "Segoe UI", Arial, sans-serif/);
assert.match(script, /const UI_LANGUAGE = browserLanguage\.toLowerCase\(\)\.startsWith\('zh'\) \? 'zh' : 'en'/);
assert.match(script, /zh:\s*\{[\s\S]*en:\s*\{/);
assert.match(script, /function applyStaticTranslations\(\)/);
assert.match(script, /function makeRuntimeStatus\(/);
assert.match(script, /function diagnosticText\(/);
assert.match(script, /function statusNeedsAttention\(status\)/);
assert.match(script, /function hideRuntimeStatus\(\)/);
assert.match(script, /function startRepairAndLocate\(\)/);
assert.match(script, /function cancelRepairAndLocate\(\)/);
assert.match(script, /message\.type === 'repairProgress'/);
assert.match(script, /nextStatus\.status === 'ready'[\s\S]*setTimeout/);
assert.match(script, /hideRuntimeStatus\(\);/);
assert.match(script, /function getBoundPanelTab\(\)/);
assert.match(script, /chrome\.tabs\.get\(currentTabId\)/);
assert.doesNotMatch(script, /chrome\.tabs\.onActivated/);
assert.match(script, /if \(tabId !== currentTabId\) return/);
assert.match(script, /Questions indexed:/);
assert.doesNotMatch(script, /URL: \$\{diagnostics\.url\}/);
assert.match(script, /const jumpSerial = \+\+jumpRequestSerial/);
assert.match(script, /url: jumpUrl,[\s\S]*requestToken: jumpRequestToken/);
assert.match(script, /!response\?\.success[\s\S]*locateFailed/);
assert.match(script, /setExportStatus\(t\('located'/);

console.log('sidepanel ui contract ok');
